// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKSxF5uHPm8tWkziZTnfUgltDkRjnYfIo',
    appId: '1:544973491115:web:c6c10c43ecdb2e3563a0ee',
    messagingSenderId: '544973491115',
    projectId: 'pos-superbootcamp',
    authDomain: 'pos-superbootcamp.firebaseapp.com',
    storageBucket: 'pos-superbootcamp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZewi0cUcy6uC8MSunp2LmATP7tSOa-9E',
    appId: '1:544973491115:android:033c7713ae21a30a63a0ee',
    messagingSenderId: '544973491115',
    projectId: 'pos-superbootcamp',
    storageBucket: 'pos-superbootcamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOQZf2vodnU-bfnr00v-yzOmmcgDhYl9A',
    appId: '1:544973491115:ios:1d2347bc3156d6bc63a0ee',
    messagingSenderId: '544973491115',
    projectId: 'pos-superbootcamp',
    storageBucket: 'pos-superbootcamp.appspot.com',
    iosBundleId: 'com.example.posSuperbootcamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKSxF5uHPm8tWkziZTnfUgltDkRjnYfIo',
    appId: '1:544973491115:web:b7c8a7069fac11f363a0ee',
    messagingSenderId: '544973491115',
    projectId: 'pos-superbootcamp',
    authDomain: 'pos-superbootcamp.firebaseapp.com',
    storageBucket: 'pos-superbootcamp.appspot.com',
  );
}
